### ISSUE TITLE
ID_injection_key not working

### ISSUE THREAD

**Issue by RayJason** [element-plus/element-plus-nuxt#82] opened 2024-01-02 07:46 UTC
Before: 
- "nuxt": "^3.8.0"
- "element-plus": "^2.4.1"
- "@element-plus/nuxt": "^1.0.6"

After:
- "nuxt": "^3.9.0"
- "element-plus": "^2.4.4"
- "@element-plus/nuxt": "^1.0.7"

There are some warmings like: 
<img width="555" alt="image" src="https://github.com/element-plus/element-plus-nuxt/assets/15711610/0904c01b-db73-4aa9-9a8d-1bff2a38c4c0">

**Comment by liruchun** [comment] 2024-01-03 03:02
Me too!
![QQ截图20240103110107](https://github.com/element-plus/element-plus-nuxt/assets/19968355/db08cf3f-eb43-4806-bcde-9fac5b4fe859)
![QQ截图20240103110126](https://github.com/element-plus/element-plus-nuxt/assets/19968355/7cba99ee-e5a7-47f4-9eb7-c133ce360692)

**Comment by tolking** [comment] 2024-01-03 12:01
Can you provide a piece of code that reproduces the issue?

**Comment by tolking** [comment] 2024-01-17 11:34
The SSR hydration error related to ID will be fixed in the next ElementPlus version.

The SSR hydration error related to z-index need to wait for Vue official repair.

**Closed by tolking** 2024-01-17 11:34 UTC

**Comment by rczdgbg** [comment] 2024-01-26 02:06
Have you given any feedback to Vue official?

**Comment by RayJason** [comment] 2024-01-26 02:16
> Have you given any feedback to Vue official?

Fixed. You can upgrade the dependencies.

**Comment by tolking** [comment] 2024-03-23 04:35
The latest version has fixed hydration errors caused by z-index

element-plus: ^2.6.2
@element-plus/nuxt: ^1.0.8
